In [ ]:
class NeauralNetwork:
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate)
        pass
    def train(self, input)
        pass
    def query(self):
        pass

In [7]:
'''
初始化函数，设置输入层，中间层和输出层的节点数----->确定网络形状和大小

'''
import scipy.special
import numpy as np

class NeauralNetwork:
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        #网络结构初始化，输入层中间层和输出层节点个数
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        #设置学习率
        self.lr = learningrate
        pass
        
        #设置初始化权重 wih为input和hidden层的权重，who为hidden和output层的权重
        #numpy.random.rand()函数输入的是数组维度，返回的是0-1之间的随机数
        self.wih = np.random.rand(self.hnodes, self.inodes) - 0.5
        self.who = np.random.rand(self.onodes, self.hnodes) - 0.5
        
        #设置激活函数 scipy.special.expit对应的是sigmoid函数
        #lambda是python的关键字，类似C语言中的宏定义，当调用self.activation_function(x）时，会自动转换为之后的函数
        self.activation_function = lambda x:scipy.special.expit(x)
        
    def train(self):
        pass
    
    def query(self, inputs):
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        print(final_outputs)
        return final_outputs
    

inputnodes = 3
hiddennodes = 3
outputnodes = 3

learningrate = 0.3
n = NeauralNetwork(inputnodes, hiddennodes, outputnodes, learningrate)
n.query([1.0, 0.5, -1.5])

[0.50400396 0.51506121 0.55836559]


array([0.50400396, 0.51506121, 0.55836559])

In [ ]:
'''
训练过程分两步：
第一步：正向传播   计算输入训练数据，给出网络的计算结果，和query()共嫩类似
第二部：反向传播   计算结果和正确结果相对比，获取误差，采用误差反向传播法更新权重
inputs_list: 输入的训练数据
targets_list: 训练数据对应的正确结果
'''
    
def train(self, inputs_list, targets_lists):
    '''
    1. 正向传播
    将inputs和outputs转化为numpy支持的二维矩阵
    
    '''
    inputs_list = np.array(inputs_list, ndmin = 2).T
    targets_list = np.array(targets_lists, ndmin = 2).T
    
    hidden_inputs = np.dot(self.wih, inputs)
    hidden_outputs = self.activation_function(hidden_inputs)
    final_inputs = np.dot(self.who, hidden_outputs)
    final_outputs = self.activation_function(final_inputs)

    '''
    2. 反向传播
    对比输出值和目标值，计算误差，计算梯度，重新更新权重参数
    
    '''
    
    outputs_errors = targets_list - final_outputs
    hidden_errors = np.dot(np.transpose(self.who), outputs_errors * final_outputs * (1 - final_outputs)) 
    
    self.who +=self.lr * np.dot(outputs_errors * final_outputs * (1 - final_outputs), np.transpose(hidden_outputs))
    self.wih +=self.lr * np.dot(hidden_errors * final_outputs * (1 - final_outputs), np.transpose(inputs))
                           

In [45]:
import scipy.special
import numpy as np

class NeauralNetwork:
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        #网络结构初始化，输入层中间层和输出层节点个数
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        #设置学习率
        self.lr = learningrate
        pass
        
        #设置初始化权重 wih为input和hidden层的权重，who为hidden和output层的权重
        #numpy.random.rand()函数输入的是数组维度，返回的是0-1之间的随机数
        self.wih = np.random.rand(self.hnodes, self.inodes) - 0.5
        self.who = np.random.rand(self.onodes, self.hnodes) - 0.5
        
        #设置激活函数 scipy.special.expit对应的是sigmoid函数
        #lambda是python的关键字，类似C语言中的宏定义，当调用self.activation_function(x）时，会自动转换为之后的函数
        self.activation_function = lambda x:scipy.special.expit(x)
        
    def train(self, inputs_list, targets_list):
        '''
        1. 正向传播
        将inputs和outputs转化为numpy支持的二维矩阵
    
        '''
        inputs = np.array(inputs_list, ndmin = 2).T
        targets = np.array(targets_list, ndmin = 2).T
    
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)

        '''
        2. 反向传播
        对比输出值和目标值，计算误差，计算梯度，重新更新权重参数
        
        '''
        outputs_errors = targets - final_outputs
        hidden_errors = np.dot(self.who.T, outputs_errors * final_outputs * (1 - final_outputs)) 
    
        self.who += self.lr * np.dot((outputs_errors * final_outputs * (1 - final_outputs)), hidden_outputs.T)
        self.wih += self.lr * np.dot((hidden_errors * hidden_outputs * (1 - hidden_outputs)), inputs.T)
    
    def query(self, inputs_list):
        
        inputs = np.array(inputs_list, ndmin=2).T
        
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        print(final_outputs)
        return final_outputs

In [27]:

'''
#把数据依靠','区分，并分别读入
all_values = training_data_list[0].split(',')

#第一个值对应的是图片的表示的数字，所以我们读取图片数据时要去掉第一个数值
print(all_values)
image_array = np.asfarray(all_values[1:]).reshape((28, 28))
print(image_array)

#最外层有10个输出节点
onodes = 10
targets = np.zeros(onodes) + 0.01
targets[int(all_values[0])] = 0.99
print(all_values[0])
print(targets)  #targets第6个元素的值是0.99，这表示图片对应的数字是5(数组是从编号0开始的).

   
#将所有数据都按照上边进行切分
for record in training_data_list:
    all_values = record.split(',')
    image_array = np.asfarray(all_values[1:])
    targets = np.zeros(output_nodes) + 0.01
    targets[int(all_values[0])] = 0.99
'''    


100
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,18,18,18,126,136,175,26,166,255,247,127,0,0,0,0,0,0,0,0,0,0,0,0,30,36,94,154,170,253,253,253,253,253,225,172,253,242,195,64,0,0,0,0,0,0,0,0,0,0,0,49,238,253,253,253,253,253,253,253,253,251,93,82,82,56,39,0,0,0,0,0,0,0,0,0,0,0,0,18,219,253,253,253,253,253,198,182,247,241,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,80,156,107,253,253,205,11,0,43,154,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,1,154,253,90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,139,253,190,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,190,253,70,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35,241,225,160,108,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,81,240,253,253,119,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [53]:
#定义网络结构具体内容  图像为28*28 所以是784个输入节点
input_nodes = 784
hidden_nodes = 100
output_nodes = 10
learaning_rate = 0.1
n = NeauralNetwork(input_nodes, hidden_nodes, output_nodes, learaning_rate)

#加入训练数据
training_data_file = open("dataset/mnist_train.csv", 'r')
training_data_list = training_data_file.readlines()
training_data_file.close()

#加入eopchs
epochs = 10
for i in range(epochs):
    for record in training_data_list:
        all_values = record.split(',')
        inputs = (np.asfarray(all_values[1:])) / 255.0 * 0.99 + 0.01
        targets = np.zeros(output_nodes) + 0.01
        targets[int(all_values[0])] = 0.99    
        n.train(inputs, targets)


In [56]:
'''
对训练好的模型开始测试
'''
#加入测试数据
test_data_file = open("dataset/mnist_test.csv", 'r')
test_data_list = test_data_file.readlines()
test_data_file.close()

scores = []

for record in test_data_list:
    all_values = record.split(',')
    inputs = (np.asfarray(all_values[1:])) / 255.0 * 0.99 + 0.01
    #图像预测
    prediction_outputs= n.query(inputs)  

    #和正确值对比
    
    correct_number = int(all_values[0])
    print('correct number', correct_number)
    
    label = np.argmax(prediction_outputs)
    print('prediction number', label) 
    if label == correct_number:
        scores.append(1)
    else:
        scores.append(0)
print(scores)

scores_array = np.asarray(scores)
print('performance = ', scores_array.sum() / scores_array.size)

[[0.04534041]
 [0.00804327]
 [0.03498349]
 [0.09329198]
 [0.13692806]
 [0.02980194]
 [0.01329939]
 [0.65248346]
 [0.10242063]
 [0.08972734]]
correct number 7
prediction number 7
[[0.18506576]
 [0.01803496]
 [0.36918185]
 [0.10339823]
 [0.00882128]
 [0.04652578]
 [0.20823471]
 [0.03889296]
 [0.16238269]
 [0.01919118]]
correct number 2
prediction number 2
[[0.0170658 ]
 [0.81310385]
 [0.13850338]
 [0.06719146]
 [0.03131937]
 [0.02904849]
 [0.03379152]
 [0.08376434]
 [0.0745495 ]
 [0.04785869]]
correct number 1
prediction number 1
[[0.44261794]
 [0.01116506]
 [0.08545232]
 [0.02317694]
 [0.01875953]
 [0.02971534]
 [0.07543248]
 [0.05295744]
 [0.02842313]
 [0.01165814]]
correct number 0
prediction number 0
[[0.32498858]
 [0.01873806]
 [0.02718118]
 [0.08416309]
 [0.70829588]
 [0.03338792]
 [0.00986729]
 [0.46260758]
 [0.09005441]
 [0.02900286]]
correct number 4
prediction number 4
[[0.01378177]
 [0.84897834]
 [0.11681982]
 [0.05748272]
 [0.03215976]
 [0.03644478]
 [0.01064474]
 [0.06241096