# 1、导入模块

In [19]:
import numpy as np

# 2、构造函数

In [20]:
class PCA():
    
    def __init__(self,weidu):
        self.weidu = weidu
        
    
    def fit_transform(self,X):
        print('原始的数组X：\n',X)
        self.n_features_ = X.shape[1]
        print('X.mean是数组X每一列的均值\n',X.mean(axis=0))
        #中心化
        X = X - X.mean(axis=0)
        print('现在的X是中心化之后的数组\n',X)
        #计算协方差矩阵
        self.covariance = (np.dot(X.T,X))/X.shape[0]
        print('协方差矩阵：\n',self.covariance)
        # 求协方差矩阵的特征值和特征向量
        eig_vals,eig_vectors = np.linalg.eig(self.covariance)
        # 获得降序排列特征值的序号
        idx = np.argsort(-eig_vals)
        # 降维矩阵
        self.components_ = eig_vectors[:,idx[:self.weidu]]
        # 对X进行降维
        return np.dot(X,self.components_)
        

# 3、调用函数，处理数据集

In [21]:
pca = PCA(weidu=2)
X = np.array([[-1,2,66,-1], [-2,6,58,-1], [-3,8,45,-2], [1,9,36,1], [2,10,62,1], [3,5,83,2]])  #导入数据，维度为4
newX=pca.fit_transform(X)
print(newX)  

原始的数组X：
 [[-1  2 66 -1]
 [-2  6 58 -1]
 [-3  8 45 -2]
 [ 1  9 36  1]
 [ 2 10 62  1]
 [ 3  5 83  2]]
X.mean是数组X每一列的均值
 [ 0.          6.66666667 58.33333333  0.        ]
现在的X是中心化之后的数组
 [[ -1.          -4.66666667   7.66666667  -1.        ]
 [ -2.          -0.66666667  -0.33333333  -1.        ]
 [ -3.           1.33333333 -13.33333333  -2.        ]
 [  1.           2.33333333 -22.33333333   1.        ]
 [  2.           3.33333333   3.66666667   1.        ]
 [  3.          -1.66666667  24.66666667   2.        ]]
协方差矩阵：
 [[ 1.75        0.375       5.75        1.125     ]
 [ 0.375       2.70833333 -8.39583333  0.3125    ]
 [ 5.75       -8.39583333 84.83333333  3.125     ]
 [ 1.125       0.3125      3.125       0.75      ]]
0
