# 1、导入要使用的模块

In [19]:
import numpy as np
from sklearn.decomposition import PCA

# 2、构造PCA函数
实现主要功能：
1、将数据集转化为矩阵
2、将数据零均值化，计算协方差矩阵
3、计算特征值和特征向量
4、返回特征值和特征向量

In [20]:
class CPCA_numpy_detail(object):
    
    def __init__(self,X,K):
            
        self.X = X  #X：数据集
        self.K = K  #k：降维后的维度
        self.centerX = []   #centerX：中心化后的数据集
        self.Covar = [] #协方差矩阵       
        self.U = []  # 样本X的降维转换矩阵
        self.Z = []  # 样本X的降维矩阵
        
        self.centerX = self._centeralizad()
        self.Covar = self._cover()
        self.U = self._U()
        self.Z = self._Z()
        
    def _centeralizad(self):  #中心化函数
        #矩阵X的中心化
        print('样本矩阵X:\n:',self.X)
        centerX = []
        mean = np.array([np.mean(attr) for attr in self.X.T])#attr是矩阵转置的一行 [10 15 23 11 42  9 11  8 11 21]#np.mean求这一行的均值
        print('样本X每一列的均值:\n',mean)  #样本X每一列的均值  [16.1 24.2 19.8]
        centerX = self.X - mean         #样本X每一列的数值减去每一列的均值
        print('样本矩阵X的中心化centrX:\n', centerX)
        return centerX
    
    def _cover(self):           #协方差函数
        #求样本矩阵X的协方差矩阵C
        C = np.dot(self.centerX.T, self.centerX)
        C = C/(np.shape(C)[0]*np.shape(C)[1])
        print('样本矩阵X的协方差矩阵C:\n', C)
        return C
    
    def _U(self):             #
        a,b = np.linalg.eig(self.Covar) #特征值赋值给a，对应特征向量赋值给b。函数doc：https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linalg.eig.html 
        print('样本集的协方差矩阵C的特征值:\n', a)
        print('样本集的协方差矩阵C的特征向量:\n', b)
        #给出特征值降序的topK的索引序列
        ind = np.argsort(-a)  #样本集的协方差矩阵C的特征值降维到K维度的索引序列:  pr-[0 1 2]
        print('样本集的协方差矩阵C的特征值降维到K维度的索引序列:\n', ind)
        #UT= [[0],[1],...[K]] UT中是X数据集 降维到0维度。。。K维度的集合
        UT =[ b[:,ind[i] ]for i in range (self.K)]  #K = 2  i = 0,1   ind[i] = 0,1  b[:,ind[i]= 取数组b的1，2列
        print('样本集的协方差矩阵C的特征向量降维到K维度:\n', UT)
        U = np.transpose(UT)
        print('%d阶降维转换矩阵U:\n'%self.K, U)
        return U
    
    def _Z(self):
        #按照Z=XU求降维矩阵Z, shape=(m,k), n是样本总数，k是降维矩阵中特征维度总数
        Z = np.dot(self.X, self.U)
        print('X shape:', np.shape(self.X))
        print('U shape:', np.shape(self.U))
        print('Z shape:', np.shape(Z))
        print('样本矩阵X的降维矩阵Z:\n', Z)
        return Z

# 3、调用CPCA函数，对X降维

In [21]:
if __name__ == '__main__':
    
    X = np.array([[10, 15, 29],
                  [15, 46, 13],
                  [23, 21, 30],
                  [11, 9,  35],
                  [42, 45, 11],
                  [9,  48, 5],
                  [11, 21, 14],
                  [8,  5,  15],
                  [11, 12, 21],
                  [21, 20, 25]])
    K = np.shape(X)[1] - 1
    print('K样本集的维度:\n', K)
    print('样本集(10行3列，10个样例，每个样例3个特征):\n', X)
    pca = CPCA_numpy_detail(X,K)

K样本集的维度:
 2
样本集(10行3列，10个样例，每个样例3个特征):
 [[10 15 29]
 [15 46 13]
 [23 21 30]
 [11  9 35]
 [42 45 11]
 [ 9 48  5]
 [11 21 14]
 [ 8  5 15]
 [11 12 21]
 [21 20 25]]
样本矩阵X:
: [[10 15 29]
 [15 46 13]
 [23 21 30]
 [11  9 35]
 [42 45 11]
 [ 9 48  5]
 [11 21 14]
 [ 8  5 15]
 [11 12 21]
 [21 20 25]]
样本X每一列的均值:
 [16.1 24.2 19.8]
样本矩阵X的中心化centrX:
 [[ -6.1  -9.2   9.2]
 [ -1.1  21.8  -6.8]
 [  6.9  -3.2  10.2]
 [ -5.1 -15.2  15.2]
 [ 25.9  20.8  -8.8]
 [ -7.1  23.8 -14.8]
 [ -5.1  -3.2  -5.8]
 [ -8.1 -19.2  -4.8]
 [ -5.1 -12.2   1.2]
 [  4.9  -4.2   5.2]]
样本矩阵X的协方差矩阵C:
 [[ 108.32222222   74.53333333  -10.08888889]
 [  74.53333333  260.62222222 -106.4       ]
 [ -10.08888889 -106.4          94.17777778]]
样本集的协方差矩阵C的特征值:
 [335.15738485  95.32771231  32.63712506]
样本集的协方差矩阵C的特征向量:
 [[-0.30253213 -0.87499307 -0.37797014]
 [-0.86718533  0.08811216  0.49012839]
 [ 0.39555518 -0.47604975  0.78543792]]
样本集的协方差矩阵C的特征值降维到K维度的索引序列:
 [0 1 2]
样本集的协方差矩阵C的特征向量降维到K维度:
 [array([-0.30253213, -0.86718533,  0.39555518]